---

- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes
    
- name: Copy to remote
  become: true
  copy:
    src: /root/project/conf
    dest: /home/ubuntu
    
- name: Install docker
  become: true
  shell: |
      cd /home/ubuntu/conf
      pwd
      ls
      chmod +x install_docker.sh
      ./install_docker.sh
  
- name: login
  become: true
  shell: |
    docker login -u {{ USERNAME }} -p {{ PASSWD }}