---

- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes
    
- name: Copy to remote
  become: true
  copy:
    src: /root/project/conf
    dest: /home/ubuntu
    
- name: Install docker
  become: true
  shell: |
      cd /home/ubuntu/conf
      chmod +x install_docker.sh
      ./install_docker.sh
  
- name: docker login
  become: true
  shell: |
    docker login -u {{ USERNAME }} -p {{ PASSWD }}

- name: install minikube
  become: true
  shell: |
    cd /home/ubuntu/conf
    chmod +x install_minikube.sh
    ./install_minikube.sh
    
- name: install kubectl
  become: true
  shell: |
    cd /home/ubuntu/conf
    chmod +x install_kubectl.sh
    ./install_kubectl.sh
    
- name: create docker user
  shell: |
    sudo docker login -u {{ USERNAME }} -p {{ PASSWD }}
    sudo gpasswd -a $USER docker
    sudo systemctl restart docker
    sudo chown "$USER":"$USER" /home/"$USER"/.docker -R
    sudo chmod g+rwx "/home/$USER/.docker" -R
    
- name: start a cluster
  shell: |
    minikube delete
    minikube start
    
- name: deploy
  shell: |
    dockerpath="miketyson40166/capstone"

    # Run in Docker Hub container with kubernetes
    kubectl run udacitycapstone\
        --image=$dockerpath\
        --port=80 --labels app=udacitycapstone
    
    # List kubernetes pods
    kubectl get pods
    
    # Forward the container port to host
    kube_status=1
    while [ $kube_status -ne 0 ]
    do
            kubectl get pods | grep Running
            kube_status=`echo $?`
            echo "waiting...."
    done
    kubectl port-forward udacitycapstone 8000:80 --address='0.0.0.0'