---

- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes
    
- name: Copy to remote
  become: true
  copy:
    src: /root/project/conf
    dest: /home/ubuntu
    
- name: Install docker
  become: true
  shell: |
      cd /home/ubuntu/conf
      chmod +x install_docker.sh
      ./install_docker.sh
  
- name: docker login
  become: true
  shell: |
    docker login -u {{ USERNAME }} -p {{ PASSWD }}

- name: install minikube
  become: true
  shell: |
    cd /home/ubuntu/conf
    chmod +x install_minikube.sh
    ./install_minikube.sh
    
- name: install kubectl
  become: true
  shell: |
    cd /home/ubuntu/conf
    chmod +x install_kubectl.sh
    ./install_kubectl.sh
    
- name: create cluster
  shell: |
    minikube start
    
- name: deploy pod
  become: true
  shell: |
    cd /home/ubuntu/conf
    chmod +x run_kubernetes.sh
    ./run_kubernetes.sh