---

- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes
    
- name: Copy to remote
  become: true
  copy:
    src: /root/project/conf
    dest: /home/ubuntu
    
- name: Install docker
  become: true
  shell: |
      cd /home/ubuntu/conf
      chmod +x install_docker.sh
      ./install_docker.sh
  
- name: docker login
  become: true
  shell: |
    docker login -u {{ USERNAME }} -p {{ PASSWD }}

- name: install minikube
  become: true
  shell: |
    cd /home/ubuntu/conf
    chmod +x install_minikube.sh
    ./install_minikube.sh
    
- name: install kubectl
  become: true
  shell: |
    cd /home/ubuntu/conf
    chmod +x install_kubectl.sh
    ./install_kubectl.sh
    
- name: create docker user
  shell: |
    sudo docker login -u {{ USERNAME }} -p {{ PASSWD }}
    sudo gpasswd -a $USER docker
    sudo systemctl restart docker
    sudo chown "$USER":"$USER" /home/"$USER"/.docker -R
    sudo chmod g+rwx "/home/$USER/.docker" -R
    
- name: start a cluster
  shell: |
    minikube delete
    minikube start
    
- name: docker login
  shell: |
    docker login -u {{ USERNAME }} -p {{ PASSWD }}

- name: deploy
  shell: |
    kubectl run udacitycapstone --image="miketyson40166/capstone" --port=80 --labels app=udacitycapstone
    
    
# - name: pending
#   become: true
#   shell: |
#     cd /home/ubuntu/conf
#     chmod +x ./run_kubernetes.sh
#     ./run_kubernetes.sh

- name: Pending
  until: pod_state.stdout|int == 0
  shell: |
    kubectl get pods | grep Running > /dev/null
    echo $?
  register: pod_state
  retries: 10
  delay: 10
    
- name: binding port
  shell: |
    kubectl port-forward --address 0.0.0.0 udacitycapstone 8000:80
  async: 100000
  poll: 0