version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.0
        auth:
          username: $USERNAME
          password: $PASSWD
        
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
              
      - setup_remote_docker:
          version: 19.03.13
              
      - run:
          name: build a Dockerfile
          command: |
            docker build --tag=capstone .
            docker images
      - run:
          name: push a docker image
          command: |
            docker login -u $USERNAME -p $PASSWD
            docker tag capstone $USERNAME/capstone
            docker push $USERNAME/capstone
                
  start-container:
    docker:
      - image: cimg/python:3.10.0
        auth:
          username: $USERNAME
          password: $PASSWD
        
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: run docker container
          command: |
            python3 -m venv venv
            . venv/bin/activate
            docker login -u $USERNAME -p $PASSWD
            docker pull $USERNAME/capstone
            docker run -itd -p 8000:80 $USERNAME/capstone
            docker container ls
            curl localhost:8000

workflows:
  default:
    jobs:
      - build    
      - start-container:
            requires: [build]
  